import { Router } from "express";
import { adminLogin, adminMe, createAdmin, getAllUsers } from "../controllers/admin.js";
import { verifyTokenAdmin } from "../utils/token-manager.js";
const adminRouter = Router();
adminRouter.post("/admin/register", createAdmin);
adminRouter.post("/admin/login", adminLogin);
// adminRouter.post("/admin/logout", adminLogout);
adminRouter.get("/admin/me", verifyTokenAdmin, adminMe);
adminRouter.get("/admin/getusers", verifyTokenAdmin, getAllUsers);
export default adminRouter;
